modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Menu-Tweaks/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG"
    description="${mod_description}"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-menu-tweaks"

[modproperties.${mod_id}]
    catalogueImageIcon="icon.png"
    catalogueBackground="catalogue_background.png"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},1.21)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${yungsapi_mc_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"